kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: <<__namespace__>>
  name: movies-logs-pv-volume-<<__namespace__>>
  labels:
    type: <<__namespace__>>
    app: movies-logs-<<__namespace__>>
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/docker_local_files_<<__namespace__>>/movies_logs-<<__namespace__>>"
    type: Directory

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: <<__namespace__>>
  name: movies-logs-pv-claim-<<__namespace__>>
  labels:
    app: movies-logs-<<__namespace__>>
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: movies-logs-<<__namespace__>>
