apiVersion: v1
kind: Secret
metadata:
  namespace: <<__namespace__>>
  name: rabbitmq-creds-loans-<<__namespace__>>
type: Opaque
stringData:
  url: "amqp://rabbit_user:your_<<__code__>>_RabbitMQ_DB_password@rabbitmq-movies-<<__namespace__>>:5672/movies"
