FROM ubuntu:18.04

EXPOSE 80

RUN apt-get clean; \
    apt-get update; \
    apt-get -y install nginx; \
    rm /etc/nginx/sites-enabled/default; \
    mkdir -p /var/log/nginx; \
    mkdir /app; \
    rm -rf /tmp/*; \
    apt-get clean; \
    rm -rf /var/log/*
ENV LANG ru_RU.UTF-8

WORKDIR /app

CMD ["nginx", "-g", "daemon off;"]
